# -*- coding: utf-8 -*-
"""Cópia de MOA3PojetoBancoA3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaS66WJosvVxbi2xc3cqszJ6JN0TDw2M
"""

contas = []
def criar_conta():
  verificador_conta_existente = False
  dados_nova_conta = {}
  dados_nova_conta['numero_conta'] = input('Digite o número da conta: \n>>> ')

  for conta_em_consulta in contas:
      if conta_em_consulta['numero_conta'] == dados_nova_conta['numero_conta']:
        verificador_conta_existente = True
        break

  if verificador_conta_existente == True:
      print('\nO número da Conta já existe. Tente novamente.')
  else:
      dados_nova_conta['saldo_conta'] = float(input('Digite o saldo da nova conta: \n>>> '))
      contas.append(dados_nova_conta)
      print('\nOperação efetuada com sucesso.')

def remover_conta():
  numero_conta_remover = input('Digite o número da conta que deseja remover: \n>>> ')
  conta_encontrada_para_remover = False
  for conta_em_consulta in contas:
      if conta_em_consulta['numero_conta'] == numero_conta_remover:
        contas.remove(conta_em_consulta)
        print('\nOperação efetuada com sucesso.')
        conta_encontrada_para_remover = True
        break
  if not conta_encontrada_para_remover:
      print('\nO número da conta não encontrada. Tente novamente.')

def listar_contas():
  if len(contas) == 0:
    print('\n Não há contas cadastradas.')
  else:
    index = 1
    for conta_em_consulta in contas:
      if conta_em_consulta['saldo_conta'] >= 0:
        status = 'Positivo'
      else:
        status = 'Negativo'
      # FORMATE STRING - f string
      print(f'{index} - Número da conta: {conta_em_consulta["numero_conta"]} | Saldo da conta R$: {conta_em_consulta["saldo_conta"]:.2f} ({status})')
      index += 1

def adiconar_saldo_em_conta():
  numero_conta = input('Digite o número da conta: \n>>> ')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      valor_credito = float(input('Digite o valor a ser credito3: \n>>> '))
      if valor_credito <0:
        print('\n Valores negativos não são aceitos. Tente novamente.')
        return
      else:
        conta_em_consulta['saldo_conta'] += valor_credito
        print('\n Operação efetuada com sucesso.')
        return
  print('\nNúmero da conta não encontrada. Tente novamente.')

def remover_saldo_em_conta():
  numero_conta = input('Digite o número da conta: \n>>> ')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      valor_debito = float(input('Digite o valor do debito: \n>>> '))
      if valor_debito <0:
        print('\n Valores negativos não são aceitos. Tente novamente.')
        return
      else:
        conta_em_consulta['saldo_conta'] -= valor_debito
        print('\n Operação efetuada com sucesso.')
        return
  print('\nNúmero da conta não encontrada. Tente novamente.')

def transferir_saldo_entre_contas():
  conta_partida_numero = input('\n Digite o número da sua conta: \n>>>')
  conta_partida_obj = None
  for conta in contas:
    if conta['numero_conta'] == conta_partida_numero:
      conta_partida_obj = conta
      break

  if conta_partida_obj is None:
    print('\n A sua conta não foi encontrada. Tente novamente. ')
    return

  conta_destino_numero = input('\n Digite o número da conta de destino: \n>>>')
  if conta_destino_numero == conta_partida_numero:
    print('\n Não é possível transferir dinheiro para a mesma conta.')
    return

  conta_destino_obj = None
  for conta in contas:
    if conta['numero_conta'] == conta_destino_numero:
      conta_destino_obj = conta
      break

  if conta_destino_obj is None:
    print('\n A conta de destino não foi encontrada. Tente novamente.')
    return

  try:
    valor_transferencia = float(input('\n Digite o valor a ser transferido: \n>>>'))
  except ValueError:
    print('\n Valor inválido. Por favor, insira um número.')
    return

  if valor_transferencia <= 0:
    print('\n Não é possível transferir um valor negativo ou zero.')
    return
  elif valor_transferencia > conta_partida_obj['saldo_conta']:
    print('\n Não é possível transferir um valor maior que seu saldo.')
    return
  else:
    conta_partida_obj['saldo_conta'] -= valor_transferencia
    conta_destino_obj['saldo_conta'] += valor_transferencia
    print('\n Operação efetuada com sucesso.')

def consultar_saldo_de_conta():
  numero_conta = input('Digite o número da conta para consultar o saldo: \n>>> ')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      if conta_em_consulta['saldo_conta'] >= 0:
        status = 'Positivo'
      else:
        status = 'Negativo'
      print(f'\n Saldo da conta: R$ {conta_em_consulta["saldo_conta"]:.2f} ({status}')
      return
  print('\ O número da conta não foi encontrado. Tente novamente.')

print(">>> Bem vindo ao Sistema Bancário <<<")

# OPERAÇÃO MENU

while True:
  print("\n### Menu ###")
  print("0 - Sair ")
  print("1 - Criar uma nova conta")
  print("2 - Remover uma conta")
  print("3 - Listar todas as contas")
  print("4 - Adicionar saldo. (creditar)")
  print("5 - Remover saldo. (debitar)")
  print("6 - Trasnferir valor entre contas.")
  print("7 - Consultar saldo de uma conta")
  numero_operacao = input('Selecione a operação que deseja realizar: \n>>> ')

  if numero_operacao == "0":
    print("Sistema Encerrado")
    break

 # OPERAÇÃO 1 - CRIAR CONTA UMA NOVA CONTA

  elif  numero_operacao == "1":
    criar_conta()

# OPERAÇÃO 2 - REMOVER UMA CONTA
  elif numero_operacao == "2":
   remover_conta()

# OPERAÇÃO 3 - LISTAR CONTAS
  elif numero_operacao == "3":
    listar_contas()

# OPERAÇÃO 4 - ADICIONAR SALDO
  elif numero_operacao == '4':
    adiconar_saldo_em_conta()

# OPERAÇÃO 5 - REMOVER SALDO
  elif numero_operacao == '5':
    remover_saldo_em_conta()

# OPERAÇÃO 6 - TRASNFERIR VALOR ENTRE CONTAS
  elif numero_operacao == '6':
    transferir_saldo_entre_contas()

# OPERAÇÃO 7 - CONSULTAR SALDO DE UMA CONTA
  elif numero_operacao == '7':
    consultar_saldo_de_conta()

# OPERAÇÃO INVALIDA
  else:
    print('\nOperação Inválida')